### ISSUE TITLE
Ajouter une version originale

### ISSUE THREAD

**Issue by Nigozziath** [Hypertopic/TraduXio#105]
Puisque nous avons un ticket pour supprimer une version originale (#93) , il nous faut la possibilité de créer une nouvelle version originale de la même manière qu'une traduction.

De plus avec similitude de plus en plus flagrante entre les versions originales et les traductions dans leur fonctionnement, il serait possible d'avoir plusieurs textes originaux pour une même œuvre.

**Comment by Nigozziath** [comment]
# Scénario 1 : Créer une version originale dans une œuvre 

## Pré-requis
Être dans une œuvre 

## Déroulement
Cliquer sur le bouton ajouter une version
Cocher la case "version originale"
Cliquer sur le bouton "créer"

## État final
On a créé une version originale pour l’œuvre, il ne reste plus qu'à l'éditer avant de sauvegarder.

## Question
Est-il possible de le faire alors que l’œuvre possède déjà une version originale ?
Quelles en seraient les conséquences ?

**Comment by benel** [comment]
Implémenté.
