### ISSUE TITLE
Discuter de la traduction d'une oeuvre (Forums)

### ISSUE THREAD

**Issue by QingZHANG92** [Hypertopic/TraduXio#86]
Chaque oeuvre fait l'objet d'un forum et pour chaque traduction, un sujet peut être ouvert. Lorsqu'un utilisateur souhaite de l'aide ou souhaite proposer une meilleure traduction, il peut ouvrir un sujet. Tout utilisateur peut ainsi contribuer sur ces forums.
Cependant, il est très difficile de naviguer entre les forums (il faut cliquer sur chaque oeuvre) et de voir les nouveaux sujets ou les nouveaux messages postés.

**Comment by QingZHANG92** [comment]
![forum](https://cloud.githubusercontent.com/assets/4447636/6867095/e39a62d6-d47e-11e4-9641-e0c4130744f0.png)

**Comment by QingZHANG92** [comment]
Scénarios possibles:
- Un étudiant a besoin d'aide sur une traduction
- Un étudiant souhaite proposer une meilleure traduction
- Un professeur souhaite voir les nouveaux messages/sujets
- Un étudiant ou un professeur souhaite être prévenu lors d'ajout de messages
- Un étudiant souhaite modifier ou supprimer un message

**Comment by stombre** [comment]
Première analyse, les scénario 1 & 2 sont similaires. On pense que la différence entre les deux c'est un consiste à créer un nouveau sujet sur le forum et l'autre consiste à répondre à un sujet existant pour autant l'intitulé du scénario ne permet pas de voir cette différence. Ces scénarios existent déjà, à voir si il est nécessaire de les changer.

**Comment by stombre** [comment]
# Scénario 5 - Un étudiant souhaite modifier ou supprimer un message
## Observation :
On a considéré que la suppression d'un message sur un forum est non pertinente et contre productive. En effet, si quelqu'un écrit une réponse, et qu'on supprime un message intermédiaire, la discutions peut perdre de son sens.

On a donc décidé de scénarisé uniquement la modification d'un message.

## Pré-requis
* Présence d'un message à modifier. 
* L'étudiant est l'auteur du message qu'il veut modifier.
* L'étudiant est sur un sujet de discutions du forum.

## Déroulement
L'étudiant a fait une erreur ou veut compléter un de ses messages existant en le modifiant.

1. L'étudiant clique sur le bouton modifier présent sur le message qu'il veut éditer.
2. L'étudiant modifie son message via une zone de saisie pré-remplie par son ancien message.
3. L'étudiant valide son message.

## Etat final
* Le nouveau message remplace l'ancien sur le forum

**Comment by ammelanie-utt** [comment]
# Scénario 3 - Visualiser les nouveaux messages et sujets d'une oeuvre

M. Paul, enseignant traducteur, souhaite bénéficier de l'utilisation du forum pour rendre son cours interactif même en dehors des heures habituelles. Le forum est un outil déjà très utilisé par les élèves, malheureusement, il est complexe de connaitre les nouveaux sujets et les sujets où il y a de l'activité. Une amélioration pourrait permettre à l'enseignant et aux étudiants d'être plus réactif et d'améliorer la qualité des échanges.

## Déroulement
Jean, étudiant, poste un message sur le forum de sa traduction afin de demander de l'aide sur un passage à traduire dans l'oeuvre originale.
M. Paul, son enseignant, se rend régulièrement sur les œuvres de ses élèves afin de pouvoir intervenir au cas où les élèves auraient des difficultés, il clique donc sur l'oeuvre que les étudiants doivent traduire. 
M. Paul se rend sur la page déjà existante qui récapitule les discussions pour cette oeuvre en cliquant sur le lien "Forum" disponible dans la barre de menu, à côté du nom de l'oeuvre, il accède ainsi à la liste des sujets disponibles. 
M. Paul visualise l'ensemble des nouveaux sujets du forum et les sujets où de nouveaux messages ont été postés à l'aide d'un indicateur visuel.

## Bilan 
M. Paul peut en cliquant sur le sujet intervenir simplement sur un sujet, si nécessaire.

**Comment by ammelanie-utt** [comment]
# Pour le scénario 4 :  Un étudiant ou un professeur souhaite être prévenu lors d'ajout de messages

## Observation

Cela nous paraît envisageable uniquement quand la notion de compte sera développée.

##  Pré-requis

M. Paul est connecté avec son compte

## Déroulement

Jean ouvre un nouveau sujet sur la traduction de l'oeuvre sur laquelle il travaille afin d'avoir l'avis de ses collègues et de son professeur.
M. Paul se rend sur le sujet en question, trouvant la question pertinente et intéressante, il coche la case "Surveiller ce sujet" afin d'être notifié quand un nouveau message est posté
Pierre, étudiant travaillant également sur l'oeuvre a une bonne piste pour la traduction de Jean, il décide donc de répondre au sujet.
M. Paul naviguant sur le site à ce moment voit un indicateur dans la barre de menu, à côté de son nom, lui signalant qu'un nouveau message a été posté
M. Paul clique sur la notification, une petite fenêtre s'affiche lui montrant le sujet de Jean, il peut en cliquant dessus directement y accéder. La notification disparaît.

**Comment by julie-romero** [comment]
Compte-rendu du 10/04/15 avec Guillaume Jeanmaire:
Les Forums sont peu utilisés car on ne peut pas voir facilement les nouveaux messages. (Les étudiants sont parfois obligés d'envoyer un email avec le lien vers le forum)
Les noms des utilisateurs ne sont pas explicites ainsi que les sujets de discussions.
Il faudrait pouvoir avoir accès à une liste de discussions sur Traduxio avec une notification des derniers messages.

**Comment by adeprez** [comment]
La notion de compte s'avérerait bénéfique pour la fonctionnalité de discussion. Elle permettrait : 
* D'identifier les participants à une discussion
* De recevoir des notifications lorsqu'un message est ajouté (par mail / dans l'interface ?)
* Identifier l'auteur d'une œuvre ou traduction

Cette fonctionnalité est donc considérée comme requise pour la discussion.

Exemples de discussions : 
* http://traduxio.sandbox.hypertopic.org/works/106f4e6a8c87e58cb0f2acdd919372d4/forum/%EC%9D%B4%EC%86%8C%EC%98%81
* http://traduxio.sandbox.hypertopic.org/works/56f9cbc3ede4cdb56ca2d805907c5805/forum/original
* http://traduxio.sandbox.hypertopic.org/works/847145cbeceb40edee0237444bdf9cb6/forum/original

**Comment by DavyPierre** [comment]
Compte-rendu du 24/04/15 avec Guillaume Jeanmaire:
-Tenir compte du fait qu'il serait bien de se logger pour participer à la discussion
-Notifications

**Comment by stombre** [comment]
# Introduction
Suite à la réunion avec Guillaume Jeanmaire (cf: message précédent). On a observé que les scénarios précédemment défini ne tenait pas compte des rôles des différents participants (rôle dans le sens : créateur de la traduction, créateur de l'oeuvre original, simple participant...). Or, ces rôles ont une importance sur le comportement du forum.

# Scénarios revisités
* Un utilisateur veut créer un message.
* Un utilisateur veut répondre à un message.
* Un utilisateur veut consulter les derniers messages présents sur le forum.
* Les participants (définit dans le scénario) veulent être notifier quand un nouveau message est créé sur le forum (nouveau sujet ou réponse à un sujet existant).
* Les participants (définit dans le scénario) veulent pouvoir modifier ou supprimer un message.

**Comment by DavyPierre** [comment]
# Scénario 1
## Observation
##Pré-Requis
##Déroulement
##Etat final

**Comment by stombre** [comment]
# Scénario 2 - Un utilisateur veut répondre à un message
## Observation :
Ici, un utilisateur est n'importe quel personne ayant accès à la version (et donc aux discutions lié à cette version).

## Pré-requis :
* Présence d'un fil de discutions
* L'utilisateur est connecté
* L'utilisateur a accès à la liste des discutions

## Déroulement :
1 - L'utilisateur ouvre un sujet de discutions.
2 - L'utilisateur clique sur le bouton répondre, présent en fin de sujet.
3 - L'utilisateur remplie le champs de saisie qui apparaît avec son message.
4 - L'utilisateur clique sur le bouton confirmer

## Etat final :
Un nouveau message apparaît sur le fil de discutions. Les utilisateurs concernés (voir scénario 4) sont notifiés.

**Comment by DavyPierre** [comment]
# Scénario 3

**Comment by stombre** [comment]
# Scénario 4 -  Les participants veulent être notifier quand un nouveau message est créé sur le forum.
## Observation :
Ici, les "participants" sont susceptible d'être plusieurs rôles différents.

## Pré-requis :
* L'utilisateur est connecté
* Un nouveau message a été posté sur le forum ou sur un fil de discutions.
* L'utilisateur a un ou plusieurs des rôles suivants :
** Il est le créateur de la version lié au fil de discutions.
** Il est le créateur du fil de discutions.
** Il a posté un message sur le fil de discutions.

## Déroulement :
1 - L'utilisateur reçoit un email lui signalant un nouveau message.
2 - L'utilisateur clique sur le lien présent sur l'email et il est redirigé sur le fil de discutions.

## Etat final :
L'utilisateur est sur le fil de discutions.

**Comment by stombre** [comment]
# Scénario 5 - Un utilisateur veut modifier un message.
## Observation :
Similaire au scénario 5 précédent.

## Pré-requis
* Présence d'un message à modifier. 
* L'utilisateur est l'auteur du message qu'il veut modifier.
* L'utilisateur est sur un sujet de discutions du forum.

## Déroulement
L'utilisateur a fait une erreur ou veut compléter un de ses messages existant en le modifiant.

1. L'utilisateur clique sur le bouton modifier présent sur le message qu'il veut éditer.
2. L'utilisateur modifie son message via une zone de saisie pré-remplie par son ancien message.
3. L'utilisateur valide son message.

## Etat final
* Le nouveau message remplace l'ancien sur le forum
* Une notification indique sur le message que celui ci a été modifié et à quelle moment.

**Comment by cyprieng** [comment]
Afin d'éviter d'avoir une discussion entre deux personnes (créateur original et créateur de la traduction) il serait préférable de notifier de la création d'une discussion tout les créateurs des autres traductions de l'oeuvre originale. En revanche on ne notifie d'un nouveau message dans une discussion que les utilisateurs ayant participé, et ceux ayant cliqué sur un bouton "Surveiller ce sujet"

Il serait bien d'avoir accès aux notifications sur le site en plus de les avoir par email. Par exemple un bouton sur la navbar avec un indicateur du nombre de nouvelles notifications.

Pour la modification il faudrait indiquer sous le message qu'il a été modifié.
On envisage de laisser la possibilité à un utilisateur de supprimer un message. En effet refuser d'autoriser la suppression n'a aucun sens si on autorise la modification. Les utilisateurs voulant supprimer leur message éditeront alors simplement leur message en indiquant un texte vide.
On indiquera que le message a été supprimé de la même manière que pour un message modifié pour plus de clarté.

Maquette
------------
![forum](https://cloud.githubusercontent.com/assets/2521188/7456398/849ca77a-f284-11e4-9ec8-17939cfd4124.png)

**Comment by DavyPierre** [comment]
Questions :

**Comment by dosdaclement** [comment]
On a distingué deux types de notification :
- celle générée lors de l'ajout d'un nouveau sujet concernant une traduction
- celle générée lors d'une réponse dans un des sujets

Dans le premier cas, par défaut, toutes les personnes ayant proposé une traduction sont notifiées ainsi que le professeur.
Dans le second, seuls les participants (ceux qui envoient des messages ou surveillent le sujet) et le professeur sont notifiés.

Concernant le mode de notification, nous avons ajouté dans les maquettes ci-dessus un bouton dédié aux notifications. On aurait donc accès aux notifications concernant le forum sur cet espace et permettrait de configurer la manière dont chacun souhaite être notifié. 
Ainsi un professeur pourra choisir par exemple d'être notifié dans tous les cas par email afin de répondre le plus rapidement possible et un élève pourra choisir d'être notifié que via l'interface de traduxio pour éviter d'avoir trop de mail.

**Comment by cyprieng** [comment]
Ajout du bouton "surveiller le sujet"
===========================

![image](https://cloud.githubusercontent.com/assets/2521188/7566860/947bc49e-f7f9-11e4-8c95-8683cdaef6a7.png)

Page liste des sujets
===============

Dans la page de la liste, il serait intéressant d'avoir un indicateur si des messages ont été postés depuis la dernière visite (en les affichant en rouge par exemple). Il serait également pratique d'avoir le bouton "Surveiller le sujet" directement sur cette page.
De plus les dates sont étranges sur cette page ex: 2015-05-06**T**10:34:46**.952Z**

Maquette :
-------------
![image](https://cloud.githubusercontent.com/assets/2521188/7567360/da74e23e-f7fc-11e4-858b-7181daa9eba5.png)

Page notifications
==============

Cliquer sur une notification nous amène à la page concerner. Et une icone de croix nous permet de supprimer une notification de la liste. 
Et un lien "Paramétrer" nous permet de configurer nos préférences en matière de notification
![image](https://cloud.githubusercontent.com/assets/2521188/7567807/64d5dddc-f7ff-11e4-946a-cc3992cc8166.png)

Remarques
=========

Le bouton discuter sur chaque traduction affiche le premier sujet créé à propos de cette traduction. Hors s'il y a plusieurs sujets, on doit ensuite cliquer sur "Liste des sujets". Il serait plus logique que le bouton discuter amène à la page de la liste des sujets de la traduction.

**Comment by GAGNAIRE-Romain** [comment]
# Récapitulatif

###### Scénario 1 - Création d'un message

- __Scénario__ : validé
- __Maquettes__ : validée
- __Tests de validation__ : aucun

###### Scénario 2 - Répondre à un message

- __Scénario__ : validé
- __Maquettes__ : validée
- __Tests de validation__ : aucun

###### Scénario 3 - Consulter les fils de discussion liés à une oeuvre

- __Scénario__ : validé
- __Maquettes__ : validée
- __Tests de validation__ : aucun

###### Scénario 4 - Notification lors de l’ajout d’un message  

- __Scénario__ : validé
- __Maquettes__ : validée
- __Tests de validation__ : aucun

###### Scénario 5 - Edition de message existant

- __Scénario__ : validé
- __Maquettes__ : validée
- __Tests de validation__ : aucun

# Maquettes modifiées

###### Scénario 1 - Création d'un message

	Ajout d'un nouveau message (sans répondre à qui que ce soit)

![forum - creer un message](https://cloud.githubusercontent.com/assets/11505086/7684787/2c5ac604-fd89-11e4-9336-af9312cb47fe.jpeg)

###### Scénario 2 - Répondre à un message

	Dans cet exemple : Réponse au message de l'utilisateur Charles

![forum - repondre a un message](https://cloud.githubusercontent.com/assets/11505086/7684794/34ae005a-fd89-11e4-916f-57b70fccfcc3.jpeg)

###### Scénario 3 - Consulter les fils de discussion liés à une oeuvre

	Simple affichage de tous les sujets disponibles

![forum - liste sujets](https://cloud.githubusercontent.com/assets/11505086/7684801/3c444176-fd89-11e4-9f1f-78ae3b5c5d15.jpeg)

###### Scénario 4 - Notification lors de l’ajout d’un message

![forum - notifications](https://cloud.githubusercontent.com/assets/11505086/7684807/48998166-fd89-11e4-83ff-270df27b64c8.jpeg)

###### Scénario 5 - Edition de message existant

	Edition d'un message existant par l'utilisateur David

![forum - editer un message existant](https://cloud.githubusercontent.com/assets/11505086/7684812/5364155c-fd89-11e4-872e-3a6f2ea38f52.jpeg)

**Comment by cyprieng** [comment]
Guillaume Jeanmaire nous a dit qu'il n'était pas forcément l'auteur du texte original. Cela pose problème pour le notifier lors d'ajout de message dans le forum.

On pourrais donc rajouter un bouton permettant de surveiller l'ensemble du forum d'une oeuvre. Le professeur devra donc cliquer sur ce bouton de l'oeuvre de ses étudiants afin d'être notifié.

Autre solution : la gestion de groupe. On définirait plusieurs rôles dans un groupe (étudiant, professeur). Et quand une oeuvre serait partagée avec ce groupe, le professeur serait automatiquement notifié.

**Comment by Luwangel** [comment]
Plutôt que de parler d'étudiant et de professeur il pourrait être pertinent de raisonner en équipe de traduction. Ne connaissant pas le métier, je suppose qu'il arrive que les traducteurs se regroupent afin de traduire une oeuvre en plusieurs langues, ou bien pour bénéficier de plusieurs relectures.

Ainsi on peut imaginer former des groupes reprenant ce fonctionnement avec des rôles tel que le chef d'équipe (= professeur ?), le ou les traducteur(s) en français, le ou les traducteur(s) en anglais, etc. Un même groupe pourra être en charge d'une ou plusieurs œuvres et, au sein d'un groupe, une personne pourra être affectée à plusieurs rôles. 

Chacun des membres recevra finalement des notifications pour la partie qui le concerne (toutes les notifications pour le chef d'équipe, seulement celles sur la traduction française pour les traducteurs français).

**Comment by GAGNAIRE-Romain** [comment]
Je pense que le système de notification devrait reposer sur du `volontariat` (*sous peine de risquer de passer pour du spam*). A mon avis, il faut laisser l'utilisateur libre de surveiller l'ensemble des sujets ou non, idépendament de son appartenance à un ou plusieurs groupes.

L'idée d'un **bouton** permettant de surveiller l'ensemble d'un forum posssède l'avantage de convenir à tout type de situation (étudiants/professeurs, chef d'équipe/traducteurs, ...)

**Comment by Luwangel** [comment]
En ce qui concerne les notifications celles-ci doivent effectivement pouvoir être désactivées (ou activées). Tout dépend du choix par défaut que nous souhaitons mettre en place. 

Soit on considère comme dans la majorité des forums qu'un sujet que l'on a créé, ou auquel on a répondu, ou bien un sujet concernant une traduction à laquelle on a participé, générera des notifications. 

Soit on considère, comme Romain le suggère, de désactiver les notifications par défaut tout en sachant qu'il y a beaucoup de chances que la majorité des utilisateurs ne l'activeront pas.

Enfin quel que soit le choix effectué je pense qu'un bouton permettant de suivre une discussion est indispensable puisqu'il pourra arriver de suivre des forums auquel on ne participe pas mais dont le contenu nous intéresse.

**Comment by benel** [comment]
Fonctionnalité peu utilisable et peu utilisée. A été supprimée.
